# Generated by Django 5.2.15 on 2026-07-02 06:45

from django.db import migrations

import apps.accounts.managers


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
