# Generated by Django 5.2.15 on 2026-08-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_bot_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="peak_rating",
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name="user",
            name="rated_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.PositiveIntegerField(db_index=True, default=1200),
        ),
    ]
