# Generated by Django 5.2.15 on 2026-08-13 06:11

from django.db import migrations, models


def copy_existing_rating(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all().iterator():
        User.objects.filter(pk=user.pk).update(
            bullet_rating=user.rating, blitz_rating=user.rating, rapid_rating=user.rating
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_peak_rating_user_rated_games_user_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blitz_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="blitz_rating",
            field=models.PositiveIntegerField(db_index=True, default=1200),
        ),
        migrations.AddField(
            model_name="user",
            name="bullet_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="bullet_rating",
            field=models.PositiveIntegerField(db_index=True, default=1200),
        ),
        migrations.AddField(
            model_name="user",
            name="rapid_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="rapid_rating",
            field=models.PositiveIntegerField(db_index=True, default=1200),
        ),
        migrations.RunPython(copy_existing_rating, migrations.RunPython.noop),
    ]
