# Generated by Django 5.2.15 on 2026-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_user_blitz_games_user_blitz_rating_user_bullet_games_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_puzzle_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="puzzle_best_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="puzzle_rating",
            field=models.PositiveIntegerField(db_index=True, default=1200),
        ),
        migrations.AddField(
            model_name="user",
            name="puzzle_streak",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
