# Generated by Django 5.2.17 on 2026-08-20 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_last_puzzle_date_user_puzzle_best_streak_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("players", "Signed-in players"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=12,
                    ),
                ),
                ("show_online_status", models.BooleanField(default=True)),
                ("allow_friend_requests", models.BooleanField(default=True)),
                ("allow_direct_messages", models.BooleanField(default=True)),
                ("allow_challenges", models.BooleanField(default=True)),
                ("notify_friend_activity", models.BooleanField(default=True)),
                ("notify_messages", models.BooleanField(default=True)),
                ("notify_tournaments", models.BooleanField(default=True)),
                ("notify_system", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
