# Generated by Django 5.2.15 on 2026-08-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_offline_sync_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="black_rating_before",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="black_rating_change",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="ratings_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="white_rating_before",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="white_rating_change",
            field=models.SmallIntegerField(default=0),
        ),
    ]
