# Generated by Django 5.2.15 on 2026-08-13 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_black_rating_before_game_black_rating_change_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sender_name", models.CharField(max_length=80)),
                ("sender_role", models.CharField(default="spectator", max_length=16)),
                ("body", models.CharField(max_length=500)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("players", "Players"),
                            ("spectators", "Spectators"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
                ("is_removed", models.BooleanField(db_index=True, default=False)),
                ("reports", models.PositiveSmallIntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="games.game",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["game", "created_at"], name="game_chat_game_time_idx"
                    )
                ],
            },
        ),
    ]
