# Generated by Django 5.2.15 on 2026-08-13 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_gamechatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="black_disconnected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="reconnect_grace_seconds",
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="game",
            name="white_disconnected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="termination",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("checkmate", "Checkmate"),
                    ("resignation", "Resignation"),
                    ("agreement", "Agreement"),
                    ("stalemate", "Stalemate"),
                    ("insufficient_material", "Insufficient material"),
                    ("seventyfive_moves", "Seventy-five moves"),
                    ("fivefold_repetition", "Fivefold repetition"),
                    ("fifty_move_rule", "Fifty-move rule"),
                    ("threefold_repetition", "Threefold repetition"),
                    ("timeout", "Timeout"),
                    ("aborted", "Aborted"),
                    ("imported", "Imported"),
                    ("abandonment", "Abandonment"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FairPlayReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("clear", "Clear"),
                            ("flagged", "Flagged"),
                            ("reviewing", "Reviewing"),
                            ("confirmed", "Confirmed violation"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="clear",
                        max_length=16,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "white_engine_match_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "black_engine_match_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("white_avg_loss_cp", models.PositiveIntegerField(default=0)),
                ("black_avg_loss_cp", models.PositiveIntegerField(default=0)),
                ("signals", models.JSONField(blank=True, default=list)),
                ("moderator_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fair_play_review",
                        to="games.game",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fair_play_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
