# Generated by Django 5.2.15 on 2026-08-10 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("swiss", "Swiss"),
                            ("round_robin", "Round robin"),
                            ("knockout", "Knockout"),
                        ],
                        default="swiss",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registration", "Registration open"),
                            ("active", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="registration",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("max_players", models.PositiveSmallIntegerField(default=16)),
                ("clock_initial_minutes", models.PositiveSmallIntegerField(default=10)),
                ("increment_seconds", models.PositiveSmallIntegerField(default=0)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "seed", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["is_public", "status", "starts_at"],
                name="tournament_public_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_players__gte", 2)),
                name="tournament_min_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("clock_initial_minutes__gte", 1)),
                name="tournament_positive_clock",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamententry",
            constraint=models.UniqueConstraint(
                fields=("tournament", "user"), name="tournament_unique_player"
            ),
        ),
    ]
