# Generated by Django 5.2.15 on 2026-08-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "In progress"), ("completed", "Completed")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TournamentPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("board_number", models.PositiveSmallIntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("white_win", "White wins"),
                            ("black_win", "Black wins"),
                            ("draw", "Draw"),
                            ("bye", "Bye"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "black_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings_as_black",
                        to="tournaments.tournamententry",
                    ),
                ),
                (
                    "white_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings_as_white",
                        to="tournaments.tournamententry",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="tournaments.tournamentround",
                    ),
                ),
            ],
            options={
                "ordering": ["round__number", "board_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="tournamentround",
            constraint=models.UniqueConstraint(
                fields=("tournament", "number"), name="tournament_unique_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentpairing",
            constraint=models.UniqueConstraint(
                fields=("round", "board_number"), name="tournament_unique_board"
            ),
        ),
    ]
