# Generated by Django 5.2.17 on 2026-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_tournament_community_and_tiebreaks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentannouncement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="tournamentmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
