# Generated by Django 5.2.17 on 2026-08-20 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_fairplayappeal"),
        ("tournaments", "0005_alter_tournamentannouncement_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentpairing",
            name="game",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_pairing",
                to="games.game",
            ),
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "invite_code",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_chess_clubs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("captain", "Captain"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=16,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tournaments.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                related_name="chess_clubs",
                through="tournaments.ClubMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SimultaneousExhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registration", "Registration open"),
                            ("active", "In progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="registration",
                        max_length=16,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("max_opponents", models.PositiveSmallIntegerField(default=20)),
                ("clock_initial_minutes", models.PositiveSmallIntegerField(default=30)),
                (
                    "host_color",
                    models.CharField(
                        choices=[("white", "White"), ("black", "Black")],
                        default="white",
                        max_length=5,
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_simuls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimulSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("board_number", models.PositiveSmallIntegerField()),
                (
                    "game",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simul_seat",
                        to="games.game",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simul_seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exhibition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="tournaments.simultaneousexhibition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamCompetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registration", "Registration open"),
                            ("active", "In progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="registration",
                        max_length=16,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("boards_per_team", models.PositiveSmallIntegerField(default=4)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamCompetitionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_points",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "board_points",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captained_team_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_entries",
                        to="tournaments.club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="tournaments.teamcompetition",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teamcompetition",
            name="clubs",
            field=models.ManyToManyField(
                related_name="competitions",
                through="tournaments.TeamCompetitionEntry",
                to="tournaments.club",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                fields=("club", "user"), name="club_unique_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="simulseat",
            constraint=models.UniqueConstraint(
                fields=("exhibition", "opponent"), name="simul_unique_opponent"
            ),
        ),
        migrations.AddConstraint(
            model_name="simulseat",
            constraint=models.UniqueConstraint(
                fields=("exhibition", "board_number"), name="simul_unique_board"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamcompetitionentry",
            constraint=models.UniqueConstraint(
                fields=("competition", "club"), name="competition_unique_club"
            ),
        ),
    ]
