# Generated by Django 5.2.15 on 2026-07-02 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gameanalysisjob",
            new_name="an_job_gs_idx",
            old_name="analysis_job_game_status_idx",
        ),
        migrations.RenameIndex(
            model_name="gameanalysisjob",
            new_name="an_job_st_time_idx",
            old_name="analysis_job_status_time_idx",
        ),
        migrations.RenameIndex(
            model_name="movereview",
            new_name="an_rev_gp_idx",
            old_name="analysis_review_game_ply_idx",
        ),
        migrations.RenameIndex(
            model_name="movereview",
            new_name="an_rev_cl_time",
            old_name="analysis_review_class_time_idx",
        ),
        migrations.RenameIndex(
            model_name="openingbookline",
            new_name="an_open_eco_idx",
            old_name="analysis_opening_active_eco_idx",
        ),
        migrations.RenameIndex(
            model_name="openingbookline",
            new_name="an_open_name_idx",
            old_name="analysis_opening_active_name_idx",
        ),
        migrations.RenameIndex(
            model_name="openingexplorerquery",
            new_name="an_open_qtime_idx",
            old_name="analysis_opening_query_time_idx",
        ),
        migrations.RenameIndex(
            model_name="positionanalysis",
            new_name="an_pos_gc_idx",
            old_name="analysis_pos_game_time_idx",
        ),
        migrations.RenameIndex(
            model_name="positionanalysis",
            new_name="an_pos_jc_idx",
            old_name="analysis_pos_job_time_idx",
        ),
    ]
