# Generated by Django 5.2.15 on 2026-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_rename_analysis_job_game_status_idx_an_job_gs_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movereview",
            name="best_line",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
