# Generated by Django 5.2.15 on 2026-08-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_movereview_best_line"),
        ("games", "0004_gamechatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movereview",
            name="move",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="games.gamemove",
            ),
        ),
    ]
