# Generated by Django 5.2.15 on 2026-08-10 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("initial_fen", models.CharField(max_length=150)),
                (
                    "solution_moves",
                    models.JSONField(
                        default=list,
                        help_text="Ordered UCI moves, starting with the solver's move.",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(db_index=True, default=1200),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        db_index=True,
                        default="intermediate",
                        max_length=16,
                    ),
                ),
                ("themes", models.JSONField(blank=True, default=list)),
                ("explanation", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["rating", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "difficulty", "rating"],
                        name="puzzle_public_level_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PuzzleAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_fen", models.CharField(max_length=150)),
                ("next_move_index", models.PositiveSmallIntegerField(default=0)),
                ("mistakes", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress"), ("solved", "Solved")],
                        db_index=True,
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="puzzles.puzzle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzle_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("puzzle", "user"), name="puzzle_one_attempt_per_user"
                    )
                ],
            },
        ),
    ]
