# Generated by Django 5.2.15 on 2026-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzleattempt",
            name="rating_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="puzzleattempt",
            name="rating_change",
            field=models.SmallIntegerField(default=0),
        ),
    ]
