# Generated by Django 5.2.17 on 2026-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0003_friendchallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendchallenge",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
