# Generated by Django 5.2.17 on 2026-08-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0004_alter_friendchallenge_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendchallenge",
            name="reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
