# Generated by Django 5.2.15 on 2026-08-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("friend_request", "Friend request"),
                            ("friend_accepted", "Friend accepted"),
                            ("friend_declined", "Friend declined"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("target_url", models.CharField(blank=True, max_length=255)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "created_at"],
                        name="notify_user_read_created_idx",
                    )
                ],
            },
        ),
    ]
