# Generated by Django 5.2.15 on 2026-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend request"),
                    ("friend_accepted", "Friend accepted"),
                    ("friend_declined", "Friend declined"),
                    ("direct_message", "Direct message"),
                    ("system", "System"),
                ],
                db_index=True,
                default="system",
                max_length=32,
            ),
        ),
    ]
